#!/usr/bin/env python3
"""Generate MANIFEST.md and the README structure table from the library itself.

    python3 tools/kb_manifest.py [--check]

MANIFEST was hand-maintained. Its word counts were wrong four separate times in
two days, each caught only by recomputing by hand, and README drifted to
claiming 77 documents and seven categories when there were 79 and eight. A
manifest that disagrees with the library is worse than none, because it is
believed. So it is generated, and `--check` fails when the committed copy is
stale — which is what the test runs.
"""
from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from kb_common import (  # noqa: E402
    CONTENT_DIRS, KB, NON_CONTENT_DIRS, SECTION_TITLES, iter_docs, read_doc)

README_ROWS = {
    "01-vocal-science-technique": "Core technique and vocal science — pedagogy, bel canto, breath, health, diction",
    "02-course-book": "Three long-form works: one training course, two complete books. See folder README",
    "03-technique-deep-dives": "Single-topic studies — registers, belting, vibrato, agility, passaggio, practice design",
    "04-artist-analyses": "Technique breakdowns of specific vocalists",
    "05-song-guides": "Song-by-song sing-through guides and song selection",
    "06-voxai-system": "The VOXAI coaching system — the method, not any one singer",
    "07-reference": "Glossary, ear training, tone/resonance reference",
    "08-external-reference": "Material by other creators — attributed, never published",
    "sources": "Reference lists extracted from the research documents — audit trail only",
    "archive": "Superseded documents, retained not deleted",
    "private": "Singer profiles and measured bodies — never published",
}


def collect():
    """Per-folder document lists, and the public totals."""
    folders: dict[str, list] = {}
    for rel, full in iter_docs():
        fm, _body, words = read_doc(full)
        folder = rel.split(os.sep)[0]
        folders.setdefault(folder, []).append((rel.replace(os.sep, "/"), fm, words))
    public = [d for f in CONTENT_DIRS for d in folders.get(f, [])
              if d[1].get("visibility") != "private"]
    return folders, len(public), sum(d[2] for d in public)


def render_manifest(folders, n_docs, n_words) -> str:
    out = ["# Manifest", "",
           "<!-- GENERATED by tools/kb_manifest.py — do not edit by hand. -->",
           "<!-- Run the tool after adding or changing a document. -->", "",
           f"**Active knowledge base: {n_docs} documents · {n_words:,} words**  "]
    extras = []
    for folder in NON_CONTENT_DIRS:
        docs = folders.get(folder, [])
        if docs:
            extras.append(f"{folder}/ {len(docs)}")
    if extras:
        out.append(f"**Not published: {' · '.join(extras)}** "
                   "(audit trail, superseded, and private singer profiles)")
    out.append("")

    for folder in CONTENT_DIRS + NON_CONTENT_DIRS:
        docs = folders.get(folder)
        if not docs:
            continue
        words = sum(d[2] for d in docs)
        title = SECTION_TITLES.get(folder, README_ROWS.get(folder, folder))
        out.append(f"## {folder}")
        out.append(f"*{title}* — {len(docs)} documents, {words:,} words")
        if folder in NON_CONTENT_DIRS:
            out.append("")
            out.append("> Excluded from the published library.")
        out.append("")
        for path, fm, words in docs:
            topics = ", ".join(fm.get("topics_list", [])) or "—"
            flag = "  **[private]**" if fm.get("visibility") == "private" else ""
            out.append(f"- `{path}` — {words:,} words · *{topics}*{flag}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_readme_table(folders) -> str:
    rows = ["| Folder | Contents | Docs |", "|---|---|---|"]
    for folder in CONTENT_DIRS + NON_CONTENT_DIRS:
        docs = folders.get(folder)
        if not docs:
            continue
        rows.append(f"| `{folder}/` | {README_ROWS.get(folder, folder)} | {len(docs)} |")
    return "\n".join(rows)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed files are stale; write nothing")
    args = ap.parse_args()

    folders, n_docs, n_words = collect()
    manifest = render_manifest(folders, n_docs, n_words)
    table = render_readme_table(folders)

    readme_path = os.path.join(KB, "README.md")
    readme = open(readme_path, encoding="utf-8").read()
    new_readme = re.sub(r"\*\*\d+ documents · ~?[\d,]+ words\*\* of knowledge, across \w+ categories\.",
                        f"**{n_docs} documents · ~{round(n_words, -3):,} words** of knowledge, "
                        f"across {len(CONTENT_DIRS)} categories.", readme, count=1)
    new_readme = re.sub(r"\| Folder \| Contents \| Docs \|\n\|---\|---\|---\|\n(?:\|.*\n)+",
                        table + "\n", new_readme, count=1)

    manifest_path = os.path.join(KB, "MANIFEST.md")
    if args.check:
        stale = []
        if open(manifest_path, encoding="utf-8").read() != manifest:
            stale.append("MANIFEST.md")
        if readme != new_readme:
            stale.append("README.md")
        if stale:
            print("FAIL  stale: " + ", ".join(stale))
            print("      Fix: python3 tools/kb_manifest.py")
            return 1
        print(f"ok    MANIFEST.md and README.md match the library "
              f"({n_docs} documents · {n_words:,} words)")
        return 0

    open(manifest_path, "w", encoding="utf-8").write(manifest)
    open(readme_path, "w", encoding="utf-8").write(new_readme)
    print(f"wrote MANIFEST.md and refreshed README.md — "
          f"{n_docs} public documents · {n_words:,} words")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
